export const defaultMenu = {
  eveningCombos: [
    {
      id: "ec1",
      tag: "Combo 1",
      name: "Chicken Feast",
      items: "Chicken Roll + Chicken Noodles",
      price: 220,
      freeWith: "Free 250ml Thumbs Up",
      available: true,
    },
    {
      id: "ec2",
      tag: "Combo 2",
      name: "Paneer Delight",
      items: "Paneer Roll + Paneer Noodles",
      price: 200,
      freeWith: "Free 250ml Thumbs Up",
      available: true,
    },
    {
      id: "ec3",
      tag: "Combo 3",
      name: "Veg Double",
      items: "Paneer Roll + Mushroom Noodles",
      price: 200,
      freeWith: "Free 250ml Cold Drink",
      available: true,
    },
  ],
  dinnerCombos: [
    {
      id: "dc1",
      tag: "Chicken Half",
      name: "Roti & Chicken Curry",
      items: "4 pcs Roti + Chicken Curry Half (4 pcs)",
      price: 180,
      freeWith: "Free 250ml Cold Drink",
      available: true,
    },
    {
      id: "dc2",
      tag: "Full Plate",
      name: "Full Chicken Thali",
      items: "8 pcs Roti + Chicken Full (7 pcs)",
      price: 350,
      freeWith: "Free 250ml Cold Drink",
      available: true,
    },
    {
      id: "dc3",
      tag: "Paneer Half",
      name: "Roti & Paneer Curry",
      items: "4 pcs Roti + Paneer Curry Half",
      price: 150,
      freeWith: "Free 250ml Cold Drink",
      available: true,
    },
    {
      id: "dc4",
      tag: "Full Plate",
      name: "Full Paneer Thali",
      items: "8 pcs Roti + Paneer Curry Full",
      price: 280,
      freeWith: "Free 250ml Cold Drink",
      available: true,
    },
    {
      id: "dc5",
      tag: "Veg Special",
      name: "Veg Rice & Mushroom",
      items: "Veg Fried Rice + Chilly Mushroom",
      price: 350,
      freeWith: "Free 250ml Cold Drink",
      available: true,
    },
    {
      id: "dc6",
      tag: "Non-Veg Special",
      name: "Egg Rice & Chilly Chicken",
      items: "Dbl Egg Chicken Fried Rice + Chilly Chicken",
      price: 400,
      freeWith: "Free 250ml Cold Drink",
      available: true,
    },
  ],
  alaCarte: [
    { id: "al1", name: "Chicken Roll", price: 120, available: true },
    { id: "al2", name: "Dbl Egg Chicken Noodles", price: 120, available: true },
    { id: "al3", name: "Paneer Roll", price: 100, available: true },
    { id: "al4", name: "Paneer Noodles", price: 100, available: true },
    { id: "al5", name: "Mushroom Noodles", price: 100, available: true },
    { id: "al6", name: "Paneer Paratha (2 pcs)", price: 120, available: true },
    { id: "al7", name: "Aloo Paratha (2 pcs)", price: 100, available: true },
    { id: "al8", name: "Roti / Phulka", price: 8, available: true, unit: "each" },
    { id: "al9", name: "Chole Half", price: 120, available: true },
    { id: "al10", name: "Chole Full", price: 200, available: true },
  ],
};
